//! Configuration synchronization between buckos CLI and buckos-build repo
//!
//! When USE flags change via `buckos use` or `buckos config`, this module
//! regenerates the Buck2-native config files in the buckos-build repository
//! so that Buck2's modifier/constraint system stays in sync.

use crate::{Config, Result, UseConfig};
use std::path::Path;

/// Sync USE flag configuration from buckos CLI config to buckos-build repo.
///
/// Writes:
/// 1. `config/install_modifiers.bzl` — global modifier list for root PACKAGE
/// 2. Per-package PACKAGE files — for per-package USE overrides
pub fn sync_config_to_repo(config: &Config) -> Result<()> {
    let repo = &config.buck_repo;

    if !repo.exists() {
        return Err(crate::Error::BuckError(format!(
            "buckos-build repository not found at {}",
            repo.display()
        )));
    }

    // 1. Write config/install_modifiers.bzl (global modifiers)
    let config_dir = repo.join("config");
    std::fs::create_dir_all(&config_dir)
        .map_err(|e| crate::Error::BuckError(format!("Failed to create config dir: {}", e)))?;

    let modifiers_path = config_dir.join("install_modifiers.bzl");
    let content = generate_modifier_bzl(&config.use_flags);
    std::fs::write(&modifiers_path, content).map_err(|e| {
        crate::Error::BuckError(format!("Failed to write install_modifiers.bzl: {}", e))
    })?;

    tracing::info!("Synced global modifiers to {}", modifiers_path.display());

    // 2. Write per-package PACKAGE files for overrides
    let packages_dir = repo.join("packages");
    for (pkg_id, flags) in &config.use_flags.package {
        if let Some(pkg_dir) = find_package_dir(&packages_dir, &pkg_id.name) {
            let package_path = pkg_dir.join("PACKAGE");
            let modifier_lines: Vec<String> = flags
                .iter()
                .map(|f| format!("    \"//use/constraints:{}-on\",", f))
                .collect();
            let content = format!(
                "# Auto-generated per-package USE override\n\
                 # Edit via: buckos use {}/{} [flags]\n\n\
                 set_modifiers([\n{}\n])\n",
                pkg_id.category,
                pkg_id.name,
                modifier_lines.join("\n")
            );
            std::fs::write(&package_path, content).map_err(|e| {
                crate::Error::BuckError(format!(
                    "Failed to write PACKAGE for {}: {}",
                    pkg_id.name, e
                ))
            })?;
            tracing::info!(
                "Synced per-package PACKAGE for {}/{}",
                pkg_id.category,
                pkg_id.name
            );
        } else {
            tracing::warn!(
                "Package directory not found for '{}/{}', skipping PACKAGE override",
                pkg_id.category,
                pkg_id.name
            );
        }
    }

    Ok(())
}

/// Generate the content of config/install_modifiers.bzl from USE config.
pub fn generate_modifier_bzl(use_config: &UseConfig) -> String {
    let mut modifiers: Vec<String> = use_config
        .global
        .iter()
        .map(|flag| format!("    \"//use/constraints:{}-on\",", flag))
        .collect();

    // Sort for deterministic output
    modifiers.sort();

    let modifiers_str = modifiers.join("\n");

    format!(
        "# Auto-generated Buck2 modifier configuration\n\
         # Generated by buckos CLI. Edit via: buckos use [flags]\n\
         # Maps USE flags to Buck2 constraint_value targets.\n\n\
         INSTALL_MODIFIERS = [\n{}\n]\n",
        modifiers_str
    )
}

/// Find a package directory by name within the packages/ tree.
fn find_package_dir(packages_dir: &Path, name: &str) -> Option<std::path::PathBuf> {
    if !packages_dir.exists() {
        return None;
    }
    find_package_dir_recursive(packages_dir, name)
}

fn find_package_dir_recursive(dir: &Path, name: &str) -> Option<std::path::PathBuf> {
    let entries = std::fs::read_dir(dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let dir_name = path.file_name()?.to_str()?;
            if dir_name == name && path.join("BUCK").exists() {
                return Some(path);
            }
            if let Some(found) = find_package_dir_recursive(&path, name) {
                return Some(found);
            }
        }
    }
    None
}
