//! Configuration synchronization between buckos CLI and buckos-build repo
//!
//! When USE flags change via `buckos use` or `buckos config`, this module
//! regenerates the Buck2-native config files in the buckos-build repository
//! so that Buck2's modifier/constraint system stays in sync.
//!
//! Two files are managed:
//! - `config/local_modifiers.bzl` — global modifiers (loaded by root PACKAGE)
//! - Per-package `PACKAGE` files — per-package modifiers via `set_cfg_modifiers()`

use crate::{Config, Result, UseConfig};
use std::path::Path;

/// Sync USE flag configuration from buckos CLI config to buckos-build repo.
///
/// Writes:
/// 1. `config/local_modifiers.bzl` — global modifier list for root PACKAGE
/// 2. Per-package PACKAGE files with `set_cfg_modifiers()` — for per-package USE overrides
pub fn sync_config_to_repo(config: &Config) -> Result<()> {
    let repo = &config.buck_repo;

    if !repo.exists() {
        return Err(crate::Error::BuckError(format!(
            "buckos-build repository not found at {}",
            repo.display()
        )));
    }

    // 1. Write config/local_modifiers.bzl (global modifiers, gitignored)
    let config_dir = repo.join("config");
    std::fs::create_dir_all(&config_dir)
        .map_err(|e| crate::Error::BuckError(format!("Failed to create config dir: {}", e)))?;

    let modifiers_path = config_dir.join("local_modifiers.bzl");
    let content = generate_local_modifiers_bzl(&config.use_flags);
    std::fs::write(&modifiers_path, content).map_err(|e| {
        crate::Error::BuckError(format!("Failed to write local_modifiers.bzl: {}", e))
    })?;

    tracing::info!("Synced global modifiers to {}", modifiers_path.display());

    // 2. Write per-package PACKAGE files with set_cfg_modifiers() (gitignored)
    let packages_dir = repo.join("packages");
    for (pkg_id, flags) in &config.use_flags.package {
        if let Some(pkg_dir) = find_package_dir(&packages_dir, &pkg_id.name) {
            let package_path = pkg_dir.join("PACKAGE");
            let content =
                generate_package_file(&format!("{}/{}", pkg_id.category, pkg_id.name), flags);
            std::fs::write(&package_path, &content).map_err(|e| {
                crate::Error::BuckError(format!(
                    "Failed to write PACKAGE for {}: {}",
                    pkg_id.name, e
                ))
            })?;
            tracing::info!(
                "Synced per-package PACKAGE for {}/{}",
                pkg_id.category,
                pkg_id.name
            );
        } else {
            tracing::warn!(
                "Package directory not found for '{}/{}', skipping PACKAGE override",
                pkg_id.category,
                pkg_id.name
            );
        }
    }

    Ok(())
}

/// Generate the content of config/local_modifiers.bzl from USE config.
pub fn generate_local_modifiers_bzl(use_config: &UseConfig) -> String {
    let mut modifiers: Vec<String> = use_config
        .global
        .iter()
        .map(|flag| format!("    \"//use/constraints:{}-on\",", flag))
        .collect();

    // Masked (disabled) flags
    for flag in &use_config.mask {
        modifiers.push(format!("    \"//use/constraints:{}-off\",", flag));
    }

    // USE_EXPAND variables (e.g., VIDEO_CARDS → video_cards_amdgpu-on)
    for (prefix, values) in &use_config.expand {
        for value in values {
            modifiers.push(format!(
                "    \"//use/constraints:{}_{}-on\",",
                prefix.to_lowercase(),
                value.to_lowercase()
            ));
        }
    }

    // Sort for deterministic output
    modifiers.sort();

    let modifiers_str = modifiers.join("\n");

    format!(
        "# Auto-generated by buckos CLI. Edit via: buckos use [flags]\n\
         # Maps USE flags to Buck2 constraint_value targets.\n\
         # This file is gitignored — local to this machine.\n\n\
         LOCAL_MODIFIERS = [\n{}\n]\n",
        modifiers_str
    )
}

/// Generate a per-package PACKAGE file using `set_cfg_modifiers()`.
///
/// This is the proper Buck2 primitive for per-directory modifier overrides.
/// Generated files are gitignored via `packages/**/PACKAGE` in .gitignore.
pub fn generate_package_file(
    package_name: &str,
    flags: &std::collections::HashSet<String>,
) -> String {
    let mut modifier_lines: Vec<String> = flags
        .iter()
        .map(|f| format!("    \"//use/constraints:{}-on\",", f))
        .collect();
    modifier_lines.sort();

    format!(
        "# Auto-generated per-package USE override\n\
         # Edit via: buckos use package {} [flags]\n\
         load(\"@prelude//cfg/modifier:set_cfg_modifiers.bzl\", \"set_cfg_modifiers\")\n\n\
         set_cfg_modifiers(cfg_modifiers = [\n{}\n])\n",
        package_name,
        modifier_lines.join("\n")
    )
}

/// Find a package directory by name within the packages/ tree.
fn find_package_dir(packages_dir: &Path, name: &str) -> Option<std::path::PathBuf> {
    if !packages_dir.exists() {
        return None;
    }
    find_package_dir_recursive(packages_dir, name)
}

fn find_package_dir_recursive(dir: &Path, name: &str) -> Option<std::path::PathBuf> {
    let entries = std::fs::read_dir(dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let dir_name = path.file_name()?.to_str()?;
            if dir_name == name && path.join("BUCK").exists() {
                return Some(path);
            }
            if let Some(found) = find_package_dir_recursive(&path, name) {
                return Some(found);
            }
        }
    }
    None
}
